#!/bin/sh -e

#	Simple kinovadrv build and install script
#################################################################################

check_make_ok() {
  if [ $? != 0 ]; then
    echo ""
    echo "Make Failed..."
    echo ""
    exit 1
  fi
}

sudo=${LIBKINOVA_SUDO-sudo}

echo "libkinova Build script"
echo "====================="
echo

$sudo rm -rf build
mkdir build
cd build
cmake ..
make
check_make_ok
$sudo make install
check_make_ok


echo
echo All Done.
echo ""
echo "NOTE: To compile programs with libkinova, you need to add:"
echo "    -lkinova"
echo "  to your compile line(s)"
echo ""
